/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * API for managing chat, orders and payments.
 * OpenAPI spec version: 1.0.0
 */

export type AuthResponseUser = {
  /** User's ID. */
  id?: string;
  /** User's email. */
  email?: string;
  /** User's role (e.g., admin, user). */
  role?: string;
};
