/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * API for managing chat, orders and payments.
 * OpenAPI spec version: 1.0.0
 */

export interface ChangePasswordRequest {
  /** The user's current password. */
  currentPassword: string;
  /** The new password the user wants to set. */
  newPassword: string;
}
