/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * API for managing chat, orders and payments.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateOrderRequest {
  /** The type of work requested. */
  workType: string;
  /** The subject area of the order. */
  subjectArea: string;
  /** Email of the client making the order. */
  email: string;
  /** Deadline for the order. */
  deadline: string;
  /** Number of pages requested. */
  pages: number;
  /** Client's phone number. */
  phoneNumber?: string;
  /** Client's first name. */
  firstName?: string;
  /** Client's last name. */
  lastName?: string;
  /** Attachments to the message. */
  files?: Blob[];
}
