/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * API for managing chat, orders and payments.
 * OpenAPI spec version: 1.0.0
 */

export type GetApiChatsChatIdMessagesNewParams = {
/**
 * ID of the last message received, used to fetch newer messages.
 */
lastMessageId: string;
};
