/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * API for managing chat, orders and payments.
 * OpenAPI spec version: 1.0.0
 */

export type GetApiOrdersSortOrder = typeof GetApiOrdersSortOrder[keyof typeof GetApiOrdersSortOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiOrdersSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
