/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * API for managing chat, orders and payments.
 * OpenAPI spec version: 1.0.0
 */

export type GetApiOrdersSortBy = typeof GetApiOrdersSortBy[keyof typeof GetApiOrdersSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiOrdersSortBy = {
  createdAt: 'createdAt',
  deadline: 'deadline',
} as const;
