/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * API for managing chat, orders and payments.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiOrdersStatus } from './getApiOrdersStatus';
import type { GetApiOrdersSortBy } from './getApiOrdersSortBy';
import type { GetApiOrdersSortOrder } from './getApiOrdersSortOrder';

export type GetApiOrdersParams = {
/**
 * Filter orders by orderId.
 */
orderId?: string;
/**
 * Filter orders by client email.
 */
email?: string;
/**
 * Filter orders by status.
 */
status?: GetApiOrdersStatus;
/**
 * Field to sort results by.
 */
sortBy?: GetApiOrdersSortBy;
/**
 * Sort order for results.
 */
sortOrder?: GetApiOrdersSortOrder;
pageNumber?: number;
pageSize?: number;
};
