/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * API for managing chat, orders and payments.
 * OpenAPI spec version: 1.0.0
 */
import type { GetChatChatId200AttachmentsItemAttachmentItem } from './getChatChatId200AttachmentsItemAttachmentItem';

export type GetChatChatId200AttachmentsItem = {
  /** List of attachment details. */
  attachment?: GetChatChatId200AttachmentsItemAttachmentItem[];
  /** The date and time the attachment was created. */
  createdAt?: string;
};
