/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * API for managing chat, orders and payments.
 * OpenAPI spec version: 1.0.0
 */
import type { MessageAttachmentsItem } from './messageAttachmentsItem';

export interface Message {
  /** Unique identifier for the message. */
  _id?: string;
  /** ID of the chat the message belongs to. */
  chatId?: string;
  /** ID of the user who sent the message. */
  sender?: string;
  /** The text content of the message. */
  content?: string;
  attachments?: MessageAttachmentsItem[];
  /** Whether the message has been read. */
  isRead?: boolean;
  /** Timestamp of when the message was created. */
  createdAt?: string;
}
