/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * API for managing chat, orders and payments.
 * OpenAPI spec version: 1.0.0
 */

export interface Order {
  /** The unique identifier for the order. */
  _id?: string;
  /** The type of work requested (e.g., essay, research). */
  workType?: string;
  /** The subject area of the order. */
  subjectArea?: string;
  /** Email of the client associated with the order. */
  email?: string;
  /** Deadline for the order. */
  deadline?: string;
  /** Number of pages required for the order. */
  pages?: number;
  /** The ID of the client who made the order. */
  client?: string;
  /** ID of the chat associated with this order. */
  chat?: string;
  /** Status of the order. */
  status?: string;
  /** Contact phone number of the client. */
  phoneNumber?: string;
  /** Timestamp of when the order was created. */
  createdAt?: string;
  /** Timestamp of the last update to the order. */
  updatedAt?: string;
}
