/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * API for managing chat, orders and payments.
 * OpenAPI spec version: 1.0.0
 */

export interface PasswordReset {
  /** The token sent to the user's email */
  token: string;
  /** The new password for the user */
  password: string;
  /** The email of the user resetting the password */
  email?: string;
}
