/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * API for managing chat, orders and payments.
 * OpenAPI spec version: 1.0.0
 */

export type PostApiFilesGetBody = {
  /** The S3 key of the file to download. */
  key: string;
  /** The custom file name for download. */
  newFileName: string;
};
