/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * API for managing chat, orders and payments.
 * OpenAPI spec version: 1.0.0
 */

export type PostApiChatsChatIdMessagesBody = {
  /** ID of the chat to send the message to. */
  chatId?: string;
  /** ID of the sender. */
  sender?: string;
  /** The message content. */
  content?: string;
  /** Attachments to the message. */
  files?: Blob[];
};
